<?php
/**
 * Password
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketplace
 *
 * API Cloud Loyalty LTM - Webpremios
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use \ArrayAccess;

/**
 * Class representing the Password model.
 *
 * 
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class Password implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $_name = 'password';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var array[]
      */
    protected static $_attributes = [
        'old_password' => ['oldPassword', 'string', null, 'setOldPassword', 'getOldPassword'],
        'new_password' => ['newPassword', 'string', null, 'setNewPassword', 'getNewPassword'],
    ];
    

    
    /**
     * Senha atual
     *
     * @var string|null
     */
    protected $old_password;

    /**
     * Nova senha
     *
     * @var string|null
     */
    protected $new_password;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->old_password = isset($data['old_password']) ? $data['old_password'] : null;
        $this->new_password = isset($data['new_password']) ? $data['new_password'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function modelName() {
        return self::$_name;
    }

    /**
     * Array of property to mappings.
     *
     * @return array[]
     */
    public function modelAttributes() {
        
        return self::$_attributes;
    }

    /**
     * Validate all the properties in the model
     *
     * Return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function isValid()
    {
        return true;
    }


    /**
     * Gets old_password.
     *
     * @return string|null
     */
    public function getOldPassword()
    {
        return $this->old_password;
    }

    /**
     * Sets old_password.
     *
     * @param string|null $old_password  Senha atual
     *
     * @return $this
     */
    public function setOldPassword($old_password = null)
    {
        $this->old_password = $old_password;

        return $this;
    }

    /**
     * Gets new_password.
     *
     * @return string|null
     */
    public function getNewPassword()
    {
        return $this->new_password;
    }

    /**
     * Sets new_password.
     *
     * @param string|null $new_password  Nova senha
     *
     * @return $this
     */
    public function setNewPassword($new_password = null)
    {
        $this->new_password = $new_password;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->$offset) ? $this->$offset : null;
    }

    /**
     * Sets value based on offset.
     * @param  string  $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        $this->$offset = null;
    }
}


