<?php
/**
 * Phone
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketplace
 *
 * API Cloud Loyalty LTM - Webpremios
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use \ArrayAccess;

/**
 * Class representing the Phone model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class Phone implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $_name = 'phone';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var array[]
      */
    protected static $_attributes = [
        'area_code' => ['areaCode', 'string', null, 'setAreaCode', 'getAreaCode'],
        'number' => ['number', 'string', null, 'setNumber', 'getNumber'],
        'type' => ['type', 'string', null, 'setType', 'getType'],
    ];
    

    /**
     * Allowed values of type
     */
    const TYPE_HOME = 'HOME';
    const TYPE_COMMERCIAL = 'COMMERCIAL';
    const TYPE_CELLULAR = 'CELLULAR';

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_HOME,
            self::TYPE_COMMERCIAL,
            self::TYPE_CELLULAR,
        ];
    }
    
    /**
     * DDD
     *
     * @var string|null
     */
    protected $area_code;

    /**
     * Número
     *
     * @var string|null
     */
    protected $number;

    /**
     * Tipo
     *
     * @var string|null
     */
    protected $type;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->area_code = isset($data['area_code']) ? $data['area_code'] : null;
        $this->number = isset($data['number']) ? $data['number'] : null;
        $this->type = isset($data['type']) ? $data['type'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($this->type, $allowedValues, true)) {
            $invalid_properties[] = sprintf(
                "invalid value for 'type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalid_properties;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function modelName() {
        return self::$_name;
    }

    /**
     * Array of property to mappings.
     *
     * @return array[]
     */
    public function modelAttributes() {
        
        return self::$_attributes;
    }

    /**
     * Validate all the properties in the model
     *
     * Return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function isValid()
    {
        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($this->type, $allowedValues)) {
            return false;
        }
        return true;
    }


    /**
     * Gets area_code.
     *
     * @return string|null
     */
    public function getAreaCode()
    {
        return $this->area_code;
    }

    /**
     * Sets area_code.
     *
     * @param string|null $area_code  DDD
     *
     * @return $this
     */
    public function setAreaCode($area_code = null)
    {
        $this->area_code = $area_code;

        return $this;
    }

    /**
     * Gets number.
     *
     * @return string|null
     */
    public function getNumber()
    {
        return $this->number;
    }

    /**
     * Sets number.
     *
     * @param string|null $number  Número
     *
     * @return $this
     */
    public function setNumber($number = null)
    {
        $this->number = $number;

        return $this;
    }

    /**
     * Gets type.
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Sets type.
     *
     * @param string|null $type  Tipo
     *
     * @return $this
     */
    public function setType($type = null)
    {
        $allowedValues = $this->getTypeAllowableValues();
        if ($type !== null && !in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->type = $type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->$offset) ? $this->$offset : null;
    }

    /**
     * Sets value based on offset.
     * @param  string  $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        $this->$offset = null;
    }
}


