<?php
/**
 * ProductSKUDetail
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketplace
 *
 * API Cloud Loyalty LTM - Webpremios
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use \ArrayAccess;
use Swagger\Server\Model\SKUImages;
use Swagger\Server\Model\Features;

/**
 * Class representing the ProductSKUDetail model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class ProductSKUDetail implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $_name = 'productSKUDetail';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var array[]
      */
    protected static $_attributes = [
        'id' => ['id', 'string', null, 'setId', 'getId'],
        'original_id' => ['originalId', 'string', null, 'setOriginalId', 'getOriginalId'],
        'status' => ['status', 'string', null, 'setStatus', 'getStatus'],
        'ean' => ['ean', 'string', null, 'setEan', 'getEan'],
        'images' => ['images', 'Swagger\Server\Model\SKUImages[]', null, 'setImages', 'getImages'],
        'features' => ['features', 'Swagger\Server\Model\Features[]', null, 'setFeatures', 'getFeatures'],
    ];
    

    
    /**
     * Identificador do SKU
     *
     * @var string|null
     */
    protected $id;

    /**
     * Identificador do SKU no parceiro
     *
     * @var string|null
     */
    protected $original_id;

    /**
     * Status do produto
     *
     * @var string|null
     */
    protected $status;

    /**
     * EAN
     *
     * @var string|null
     */
    protected $ean;

    /**
     * Imagens
     *
     * @var SKUImages[]|null
     */
    protected $images;

    /**
     * Características
     *
     * @var Features[]|null
     */
    protected $features;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->id = isset($data['id']) ? $data['id'] : null;
        $this->original_id = isset($data['original_id']) ? $data['original_id'] : null;
        $this->status = isset($data['status']) ? $data['status'] : null;
        $this->ean = isset($data['ean']) ? $data['ean'] : null;
        $this->images = isset($data['images']) ? $data['images'] : null;
        $this->features = isset($data['features']) ? $data['features'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function modelName() {
        return self::$_name;
    }

    /**
     * Array of property to mappings.
     *
     * @return array[]
     */
    public function modelAttributes() {
        
        return self::$_attributes;
    }

    /**
     * Validate all the properties in the model
     *
     * Return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function isValid()
    {
        return true;
    }


    /**
     * Gets id.
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Sets id.
     *
     * @param string|null $id  Identificador do SKU
     *
     * @return $this
     */
    public function setId($id = null)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets original_id.
     *
     * @return string|null
     */
    public function getOriginalId()
    {
        return $this->original_id;
    }

    /**
     * Sets original_id.
     *
     * @param string|null $original_id  Identificador do SKU no parceiro
     *
     * @return $this
     */
    public function setOriginalId($original_id = null)
    {
        $this->original_id = $original_id;

        return $this;
    }

    /**
     * Gets status.
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Sets status.
     *
     * @param string|null $status  Status do produto
     *
     * @return $this
     */
    public function setStatus($status = null)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Gets ean.
     *
     * @return string|null
     */
    public function getEan()
    {
        return $this->ean;
    }

    /**
     * Sets ean.
     *
     * @param string|null $ean  EAN
     *
     * @return $this
     */
    public function setEan($ean = null)
    {
        $this->ean = $ean;

        return $this;
    }

    /**
     * Gets images.
     *
     * @return SKUImages[]|null
     */
    public function getImages()
    {
        return $this->images;
    }

    /**
     * Sets images.
     *
     * @param SKUImages[]|null $images  Imagens
     *
     * @return $this
     */
    public function setImages(array $images = null)
    {
        $this->images = $images;

        return $this;
    }

    /**
     * Gets features.
     *
     * @return Features[]|null
     */
    public function getFeatures()
    {
        return $this->features;
    }

    /**
     * Sets features.
     *
     * @param Features[]|null $features  Características
     *
     * @return $this
     */
    public function setFeatures(array $features = null)
    {
        $this->features = $features;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->$offset) ? $this->$offset : null;
    }

    /**
     * Sets value based on offset.
     * @param  string  $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        $this->$offset = null;
    }
}


