<?php
/**
 * PurchaseAuthConversionRate
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketplace
 *
 * API Cloud Loyalty LTM - Webpremios
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use \ArrayAccess;

/**
 * Class representing the PurchaseAuthConversionRate model.
 *
 * 
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class PurchaseAuthConversionRate implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $_name = 'purchaseAuthConversionRate';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var array[]
      */
    protected static $_attributes = [
        'vendor_id' => ['vendorId', 'string', null, 'setVendorId', 'getVendorId'],
        'conversion_factor' => ['conversionFactor', 'float', 'decimal', 'setConversionFactor', 'getConversionFactor'],
    ];
    

    
    /**
     * Identificador do parceiro
     *
     * @var string|null
     */
    protected $vendor_id;

    /**
     * Fator de conversão
     *
     * @var float|null
     */
    protected $conversion_factor;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->vendor_id = isset($data['vendor_id']) ? $data['vendor_id'] : null;
        $this->conversion_factor = isset($data['conversion_factor']) ? $data['conversion_factor'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function modelName() {
        return self::$_name;
    }

    /**
     * Array of property to mappings.
     *
     * @return array[]
     */
    public function modelAttributes() {
        
        return self::$_attributes;
    }

    /**
     * Validate all the properties in the model
     *
     * Return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function isValid()
    {
        return true;
    }


    /**
     * Gets vendor_id.
     *
     * @return string|null
     */
    public function getVendorId()
    {
        return $this->vendor_id;
    }

    /**
     * Sets vendor_id.
     *
     * @param string|null $vendor_id  Identificador do parceiro
     *
     * @return $this
     */
    public function setVendorId($vendor_id = null)
    {
        $this->vendor_id = $vendor_id;

        return $this;
    }

    /**
     * Gets conversion_factor.
     *
     * @return float|null
     */
    public function getConversionFactor()
    {
        return $this->conversion_factor;
    }

    /**
     * Sets conversion_factor.
     *
     * @param float|null $conversion_factor  Fator de conversão
     *
     * @return $this
     */
    public function setConversionFactor($conversion_factor = null)
    {
        $this->conversion_factor = $conversion_factor;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->$offset) ? $this->$offset : null;
    }

    /**
     * Sets value based on offset.
     * @param  string  $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        $this->$offset = null;
    }
}


