<?php
/**
 * PurchaseCustomer
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketplace
 *
 * API Cloud Loyalty LTM - Webpremios
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use \ArrayAccess;
use Swagger\Server\Model\Phone;
use Swagger\Server\Model\Address;

/**
 * Class representing the PurchaseCustomer model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class PurchaseCustomer implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $_name = 'purchaseCustomer';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var array[]
      */
    protected static $_attributes = [
        'name' => ['name', 'string', null, 'setName', 'getName'],
        'document_number' => ['documentNumber', 'string', null, 'setDocumentNumber', 'getDocumentNumber'],
        'rg' => ['rg', 'string', null, 'setRg', 'getRg'],
        'email' => ['email', 'string', null, 'setEmail', 'getEmail'],
        'address' => ['address', 'Swagger\Server\Model\Address', null, 'setAddress', 'getAddress'],
        'phones' => ['phones', 'Swagger\Server\Model\Phone[]', null, 'setPhones', 'getPhones'],
    ];
    

    
    /**
     * Nome do cliente
     *
     * @var string|null
     */
    protected $name;

    /**
     * Documento ex: CPF, CNPJ
     *
     * @var string|null
     */
    protected $document_number;

    /**
     * RG
     *
     * @var string|null
     */
    protected $rg;

    /**
     * E-mail
     *
     * @var string|null
     */
    protected $email;

    /**     * @var Address|null
     */
    protected $address;

    /**
     * Telefones
     *
     * @var Phone[]|null
     */
    protected $phones;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->name = isset($data['name']) ? $data['name'] : null;
        $this->document_number = isset($data['document_number']) ? $data['document_number'] : null;
        $this->rg = isset($data['rg']) ? $data['rg'] : null;
        $this->email = isset($data['email']) ? $data['email'] : null;
        $this->address = isset($data['address']) ? $data['address'] : null;
        $this->phones = isset($data['phones']) ? $data['phones'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function modelName() {
        return self::$_name;
    }

    /**
     * Array of property to mappings.
     *
     * @return array[]
     */
    public function modelAttributes() {
        
        return self::$_attributes;
    }

    /**
     * Validate all the properties in the model
     *
     * Return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function isValid()
    {
        return true;
    }


    /**
     * Gets name.
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Sets name.
     *
     * @param string|null $name  Nome do cliente
     *
     * @return $this
     */
    public function setName($name = null)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Gets document_number.
     *
     * @return string|null
     */
    public function getDocumentNumber()
    {
        return $this->document_number;
    }

    /**
     * Sets document_number.
     *
     * @param string|null $document_number  Documento ex: CPF, CNPJ
     *
     * @return $this
     */
    public function setDocumentNumber($document_number = null)
    {
        $this->document_number = $document_number;

        return $this;
    }

    /**
     * Gets rg.
     *
     * @return string|null
     */
    public function getRg()
    {
        return $this->rg;
    }

    /**
     * Sets rg.
     *
     * @param string|null $rg  RG
     *
     * @return $this
     */
    public function setRg($rg = null)
    {
        $this->rg = $rg;

        return $this;
    }

    /**
     * Gets email.
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Sets email.
     *
     * @param string|null $email  E-mail
     *
     * @return $this
     */
    public function setEmail($email = null)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Gets address.
     *
     * @return Address|null
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Sets address.
     *
     * @param Address|null $address
     *
     * @return $this
     */
    public function setAddress(Address $address = null)
    {
        $this->address = $address;

        return $this;
    }

    /**
     * Gets phones.
     *
     * @return Phone[]|null
     */
    public function getPhones()
    {
        return $this->phones;
    }

    /**
     * Sets phones.
     *
     * @param Phone[]|null $phones  Telefones
     *
     * @return $this
     */
    public function setPhones(array $phones = null)
    {
        $this->phones = $phones;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->$offset) ? $this->$offset : null;
    }

    /**
     * Sets value based on offset.
     * @param  string  $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        $this->$offset = null;
    }
}


