<?php
/**
 * RequestAddCartItem
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketplace
 *
 * API Cloud Loyalty LTM - Webpremios
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use \ArrayAccess;

/**
 * Class representing the RequestAddCartItem model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class RequestAddCartItem implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $_name = 'requestAddCartItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var array[]
      */
    protected static $_attributes = [
        'vendor_id' => ['vendorId', 'string', null, 'setVendorId', 'getVendorId'],
        'product_sku_id' => ['productSkuId', 'string', null, 'setProductSkuId', 'getProductSkuId'],
    ];
    

    
    /**
     * Identificador do parceiro
     *
     * @var string
     */
    protected $vendor_id;

    /**
     * Identificador do SKU
     *
     * @var string
     */
    protected $product_sku_id;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->vendor_id = isset($data['vendor_id']) ? $data['vendor_id'] : null;
        $this->product_sku_id = isset($data['product_sku_id']) ? $data['product_sku_id'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->vendor_id === null) {
            $invalid_properties[] = "'vendor_id' can't be null";
        }
        if ($this->product_sku_id === null) {
            $invalid_properties[] = "'product_sku_id' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function modelName() {
        return self::$_name;
    }

    /**
     * Array of property to mappings.
     *
     * @return array[]
     */
    public function modelAttributes() {
        
        return self::$_attributes;
    }

    /**
     * Validate all the properties in the model
     *
     * Return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function isValid()
    {
        if ($this->vendor_id === null) {
            return false;
        }
        if ($this->product_sku_id === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets vendor_id.
     *
     * @return string
     */
    public function getVendorId()
    {
        return $this->vendor_id;
    }

    /**
     * Sets vendor_id.
     *
     * @param string $vendor_id  Identificador do parceiro
     *
     * @return $this
     */
    public function setVendorId($vendor_id)
    {
        $this->vendor_id = $vendor_id;

        return $this;
    }

    /**
     * Gets product_sku_id.
     *
     * @return string
     */
    public function getProductSkuId()
    {
        return $this->product_sku_id;
    }

    /**
     * Sets product_sku_id.
     *
     * @param string $product_sku_id  Identificador do SKU
     *
     * @return $this
     */
    public function setProductSkuId($product_sku_id)
    {
        $this->product_sku_id = $product_sku_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->$offset) ? $this->$offset : null;
    }

    /**
     * Sets value based on offset.
     * @param  string  $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        $this->$offset = null;
    }
}


