<?php
/**
 * CarrinhoApiInterfaceTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Tests\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketplace
 *
 * API Cloud Loyalty LTM - Webpremios
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Server\Tests\Api;

use \Swagger\Server\Configuration;
use \Swagger\Server\ApiClient;
use \Swagger\Server\ApiException;
use \Swagger\Server\ObjectSerializer;

/**
 * CarrinhoApiInterfaceTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Server\Tests\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CarrinhoApiInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for cartsMeGet
     *
     * Obtém um carrinho.
     *
     */
    public function testCartsMeGet()
    {
    }

    /**
     * Test case for cartsMeItemsPost
     *
     * Adicionar item no carrinho.
     *
     */
    public function testCartsMeItemsPost()
    {
    }

    /**
     * Test case for cartsMeItemsSkuIdDelete
     *
     * Remove item do carrinho.
     *
     */
    public function testCartsMeItemsSkuIdDelete()
    {
    }

    /**
     * Test case for cartsMeItemsSkuIdPut
     *
     * Alterar item no carrinho.
     *
     */
    public function testCartsMeItemsSkuIdPut()
    {
    }

    /**
     * Test case for cartsMeShippingPut
     *
     * Adiciona dados de entrega no carrinho.
     *
     */
    public function testCartsMeShippingPut()
    {
    }

    /**
     * Test case for cartsMeShippingRatesGet
     *
     * Calcula o frete do carrinho para um CEP.
     *
     */
    public function testCartsMeShippingRatesGet()
    {
    }
}
