<?php
/**
 * CompraApiInterfaceTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Tests\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketplace
 *
 * API Cloud Loyalty LTM - Webpremios
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Server\Tests\Api;

use \Swagger\Server\Configuration;
use \Swagger\Server\ApiClient;
use \Swagger\Server\ApiException;
use \Swagger\Server\ObjectSerializer;

/**
 * CompraApiInterfaceTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Server\Tests\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CompraApiInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for purchasesAuthorizePost
     *
     * Cria e autoriza uma compra.
     *
     */
    public function testPurchasesAuthorizePost()
    {
    }

    /**
     * Test case for purchasesIdConfirmPost
     *
     * Confirma uma compra.
     *
     */
    public function testPurchasesIdConfirmPost()
    {
    }

    /**
     * Test case for purchasesIdGet
     *
     * Obtém um compra.
     *
     */
    public function testPurchasesIdGet()
    {
    }

    /**
     * Test case for purchasesMeGet
     *
     * Obtém compras.
     *
     */
    public function testPurchasesMeGet()
    {
    }

    /**
     * Test case for purchasesPost
     *
     * Cria uma compra.
     *
     */
    public function testPurchasesPost()
    {
    }
}
