<?php
/**
 * ParticipanteApiInterfaceTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Tests\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketplace
 *
 * API Cloud Loyalty LTM - Webpremios
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Server\Tests\Api;

use \Swagger\Server\Configuration;
use \Swagger\Server\ApiClient;
use \Swagger\Server\ApiException;
use \Swagger\Server\ObjectSerializer;

/**
 * ParticipanteApiInterfaceTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Server\Tests\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ParticipanteApiInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for participantsMeBalanceGet
     *
     * Obtém o saldo do participante.
     *
     */
    public function testParticipantsMeBalanceGet()
    {
    }

    /**
     * Test case for participantsMeExtractGet
     *
     * Obtém o extrato do participante.
     *
     */
    public function testParticipantsMeExtractGet()
    {
    }

    /**
     * Test case for participantsMeGet
     *
     * Obtém um participante.
     *
     */
    public function testParticipantsMeGet()
    {
    }

    /**
     * Test case for participantsMePasswordPut
     *
     * Altera a senha do participante.
     *
     */
    public function testParticipantsMePasswordPut()
    {
    }

    /**
     * Test case for participantsMePut
     *
     * Altera um participante.
     *
     */
    public function testParticipantsMePut()
    {
    }

    /**
     * Test case for participantsPost
     *
     * Cria um novo participante.
     *
     */
    public function testParticipantsPost()
    {
    }

    /**
     * Test case for participantsUsernamePasswordResetPost
     *
     * Reseta a senha do participante.
     *
     */
    public function testParticipantsUsernamePasswordResetPost()
    {
    }
}
