<?php
/**
 * BalanceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Tests\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketplace
 *
 * API Cloud Loyalty LTM - Webpremios
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Server\Tests\Model;

/**
 * BalanceTest Class Doc Comment
 *
 * @category    Class */
// * @description 
/**
 * @package     Swagger\Server\Tests\Model
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BalanceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Balance"
     */
    public function testBalance()
    {
    }

    /**
     * Test attribute "points_value"
     */
    public function testPropertyPointsValue()
    {
    }

    /**
     * Test attribute "points_value_onhold"
     */
    public function testPropertyPointsValueOnhold()
    {
    }

    /**
     * Test attribute "total_points_value"
     */
    public function testPropertyTotalPointsValue()
    {
    }

    /**
     * Test attribute "total_credit_points_value"
     */
    public function testPropertyTotalCreditPointsValue()
    {
    }

    /**
     * Test attribute "total_debit_points_value"
     */
    public function testPropertyTotalDebitPointsValue()
    {
    }
}
