<?php
/**
 * SearchTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Tests\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketplace
 *
 * API Cloud Loyalty LTM - Webpremios
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Server\Tests\Model;

/**
 * SearchTest Class Doc Comment
 *
 * @category    Class */
// * @description 
/**
 * @package     Swagger\Server\Tests\Model
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SearchTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Search"
     */
    public function testSearch()
    {
    }

    /**
     * Test attribute "products"
     */
    public function testPropertyProducts()
    {
    }

    /**
     * Test attribute "categories"
     */
    public function testPropertyCategories()
    {
    }

    /**
     * Test attribute "brands"
     */
    public function testPropertyBrands()
    {
    }

    /**
     * Test attribute "vendors"
     */
    public function testPropertyVendors()
    {
    }

    /**
     * Test attribute "lower_price"
     */
    public function testPropertyLowerPrice()
    {
    }

    /**
     * Test attribute "higher_price"
     */
    public function testPropertyHigherPrice()
    {
    }

    /**
     * Test attribute "page_index"
     */
    public function testPropertyPageIndex()
    {
    }

    /**
     * Test attribute "last_page"
     */
    public function testPropertyLastPage()
    {
    }
}
