<?php

/**
 * AutorizaoController
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Controller
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketplace
 *
 * API Cloud Loyalty LTM - Webpremios
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Controller;

use \Exception;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Swagger\Server\Api\AutorizaoApiInterface;
use Swagger\Server\Model\Token;
use Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;

/**
 * AutorizaoController Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Server\Controller
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AutorizaoController extends Controller
{

    /**
     * Operation accessTokenPost
     *
     * Gera um token
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function accessTokenPostAction(Request $request)
    {
        // Authentication 'Authorization' required
        // Set key with prefix in header
        $securityAuthorization = $request->headers->get('Authorization');
        // Handle form params
        $grant_type = $this->fromForm($request->request->get('grant_type'), 'string');
        // Handle form params
        $user = $this->fromForm($request->request->get('user'), 'string');
        // Handle form params
        $password = $this->fromForm($request->request->get('password'), 'string');
        // Handle form params
        $campaign_id = $this->fromForm($request->request->get('campaign_id'), 'string');

        // Parse incoming parameters
        // Verify the required parameter 'grant_type' is set
        if ($grant_type === null) {
            return $this->createBadRequestResponse('Missing the required parameter $grant_type when calling accessTokenPost');
        }
        // Verify the required parameter 'campaign_id' is set
        if ($campaign_id === null) {
            return $this->createBadRequestResponse('Missing the required parameter $campaign_id when calling accessTokenPost');
        }

        // Call the API interface
        try {
            $handler = $this->getApiHandler();

            // Set authentication method 'Authorization'
            $handler->setAuthorization($securityAuthorization);
            // Expecting a return value (exception otherwise)
            $result = $handler->accessTokenPost($grant_type, $campaign_id, $user, $password);

            // Handle 201 response: Operação realizada com sucesso.
            $content = $this->serialize($result, 'json');
            return new Response($content, 201, [
                'Content-Type' => 'application/json',
                'X-Swagger-Message' => 'Operação realizada com sucesso.',
            ]);
            // Handle 500 response: Erro Interno.
            $content = $this->serialize($result, 'json');
            return new Response($content, 500, [
                'Content-Type' => 'application/json',
                'X-Swagger-Message' => 'Erro Interno.',
            ]);
        } catch (BadRequestHttpException $exception) {
            // Requisição mal formada.
            return $this->createErrorResponse($exception);
        } catch (UnauthorizedHttpException $exception) {
            // Não autenticado.
            return $this->createErrorResponse($exception);
        } catch (AccessDeniedHttpException $exception) {
            // O acesso ao recurso foi negado.
            return $this->createErrorResponse($exception);
        } catch (NotFoundHttpException $exception) {
            // Recurso não encontrado.
            return $this->createErrorResponse($exception);
        } catch (Exception $fallthrough) {
            return $this->createErrorResponse(new HttpException(500, 'An unsuspected error occurred.', $fallthrough));
        }
    }

    /**
     * Returns the handler for this API controller.
     * @return AutorizaoApiInterface
     */
    public function getApiHandler()
    {
        return $this->get('swagger_server.api.api_server')->getApiHandler('autorizao');
    }
}
