<?php

/**
 * BuscaController
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Controller
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketplace
 *
 * API Cloud Loyalty LTM - Webpremios
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Controller;

use \Exception;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Swagger\Server\Api\BuscaApiInterface;
use Swagger\Server\Model\BusinessErrorMessage;
use Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Swagger\Server\Model\Search;
use Symfony\Component\HttpKernel\Exception\UnprocessableEntityHttpException;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;

/**
 * BuscaController Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Server\Controller
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BuscaController extends Controller
{

    /**
     * Operation searchGet
     *
     * Obtém produtos
     *
     * @param Request $request The Symfony request to handle.
     * @return Response The Symfony response.
     */
    public function searchGetAction(Request $request)
    {
        // Authentication 'access_token' required
        // Set key with prefix in header
        $securityaccess_token = $request->headers->get('access_token');
        // Authentication 'client_id' required
        // Set key with prefix in header
        $securityclient_id = $request->headers->get('client_id');
        // Handle query params
        $sort = $this->fromQuery($request->query->get('sort'), 'string');
        // Handle query params
        $term = $this->fromQuery($request->query->get('term'), 'string');
        // Handle query params
        $vendor_id = $this->fromQuery($request->query->get('vendor_id'), 'string');
        // Handle query params
        $category_id = $this->fromQuery($request->query->get('category_id'), 'string');
        // Handle query params
        $subcategory_id = $this->fromQuery($request->query->get('subcategory_id'), 'string');
        // Handle query params
        $brand_id = $this->fromQuery($request->query->get('brand_id'), 'string');
        // Handle query params
        $min_price = $this->fromQuery($request->query->get('min_price'), 'float');
        // Handle query params
        $max_price = $this->fromQuery($request->query->get('max_price'), 'float');
        // Handle query params
        $_offset = $this->fromQuery($request->query->get('_offset'), 'float');
        // Handle query params
        $_limit = $this->fromQuery($request->query->get('_limit'), 'float');

        // Parse incoming parameters
        // Verify the required parameter 'sort' is set
        if ($sort === null) {
            return $this->createBadRequestResponse('Missing the required parameter $sort when calling searchGet');
        }
        // Verify the required parameter '_offset' is set
        if ($_offset === null) {
            return $this->createBadRequestResponse('Missing the required parameter $_offset when calling searchGet');
        }
        // Verify the required parameter '_limit' is set
        if ($_limit === null) {
            return $this->createBadRequestResponse('Missing the required parameter $_limit when calling searchGet');
        }

        // Call the API interface
        try {
            $handler = $this->getApiHandler();

            // Set authentication method 'access_token'
            $handler->setaccess_token($securityaccess_token);
            // Set authentication method 'client_id'
            $handler->setclient_id($securityclient_id);
            // Expecting a return value (exception otherwise)
            $result = $handler->searchGet($sort, $_offset, $_limit, $term, $vendor_id, $category_id, $subcategory_id, $brand_id, $min_price, $max_price);

            // Handle 200 response: Operação realizada com sucesso.
            $content = $this->serialize($result, 'json');
            return new Response($content, 200, [
                'Content-Type' => 'application/json',
                'X-Swagger-Message' => 'Operação realizada com sucesso.',
            ]);
            // Handle 500 response: Erro Interno.
            $content = $this->serialize($result, 'json');
            return new Response($content, 500, [
                'Content-Type' => 'application/json',
                'X-Swagger-Message' => 'Erro Interno.',
            ]);
        } catch (BadRequestHttpException $exception) {
            // Requisição mal formada.
            return $this->createErrorResponse($exception);
        } catch (UnauthorizedHttpException $exception) {
            // Requisição requer autenticação.
            return $this->createErrorResponse($exception);
        } catch (AccessDeniedHttpException $exception) {
            // O acesso ao recurso foi negado.
            return $this->createErrorResponse($exception);
        } catch (NotFoundHttpException $exception) {
            // Recurso não encontrado.
            return $this->createErrorResponse($exception);
        } catch (UnprocessableEntityHttpException $exception) {
            // Requisição não processável.
            return $this->createErrorResponse($exception);
        } catch (Exception $fallthrough) {
            return $this->createErrorResponse(new HttpException(500, 'An unsuspected error occurred.', $fallthrough));
        }
    }

    /**
     * Returns the handler for this API controller.
     * @return BuscaApiInterface
     */
    public function getApiHandler()
    {
        return $this->get('swagger_server.api.api_server')->getApiHandler('busca');
    }
}
