<?php
/**
 * CompraApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketplace
 *
 * API Cloud Loyalty LTM - Webpremios
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Api;

use Swagger\Server\Model\Purchase;
use Swagger\Server\Model\BusinessErrorMessage;
use Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Swagger\Server\Model\PurchasePost;
use Swagger\Server\Model\PurchaseAdd;
use Symfony\Component\HttpKernel\Exception\UnprocessableEntityHttpException;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Swagger\Server\Model\PurchaseAuthorize;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;

/**
 * CompraApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  Swagger\Server\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
interface CompraApiInterface
{

    /**
     * Sets authentication method access_token
     *
     * @param string $value Value of the access_token authentication method.
     *
     * @return void
     */
    public function setaccess_token($value);

    /**
     * Sets authentication method client_id
     *
     * @param string $value Value of the client_id authentication method.
     *
     * @return void
     */
    public function setclient_id($value);

    /**
     * Operation purchasesAuthorizePost
     *
     * Cria e autoriza uma compra
     *
     * @param  PurchaseAuthorize $purchase   (required)
     *
     * @return PurchaseAdd  Operação realizada com sucesso.
     *
     * @throws BadRequestHttpException  Requisição mal formada.
     * @throws UnauthorizedHttpException  Requisição requer autenticação.
     * @throws AccessDeniedHttpException  O acesso ao recurso foi negado.
     * @throws NotFoundHttpException  Recurso não encontrado.
     * @throws UnprocessableEntityHttpException  Requisição não processável.
     * @return void  Erro Interno.
     *
     */
    public function purchasesAuthorizePost(PurchaseAuthorize $purchase);

    /**
     * Operation purchasesIdConfirmPost
     *
     * Confirma uma compra
     *
     * @param  string $id  Identificador da compra (required)
     *
     * @return void  Operação realizada com sucesso.
     *
     * @throws BadRequestHttpException  Requisição mal formada.
     * @throws UnauthorizedHttpException  Requisição requer autenticação.
     * @throws AccessDeniedHttpException  O acesso ao recurso foi negado.
     * @throws NotFoundHttpException  Recurso não encontrado.
     * @throws UnprocessableEntityHttpException  Requisição não processável.
     * @return void  Erro Interno.
     *
     */
    public function purchasesIdConfirmPost($id);

    /**
     * Operation purchasesIdGet
     *
     * Obtém um compra
     *
     * @param  string $id  Identificador da compra (required)
     *
     * @return Purchase  Operação realizada com sucesso.
     *
     * @throws BadRequestHttpException  Requisição mal formada.
     * @throws UnauthorizedHttpException  Requisição requer autenticação.
     * @throws AccessDeniedHttpException  O acesso ao recurso foi negado.
     * @throws NotFoundHttpException  Recurso não encontrado.
     * @throws UnprocessableEntityHttpException  Requisição não processável.
     * @return void  Erro Interno.
     *
     */
    public function purchasesIdGet($id);

    /**
     * Operation purchasesMeGet
     *
     * Obtém compras
     *
     *
     * @return Purchase[]  Operação realizada com sucesso.
     *
     * @throws BadRequestHttpException  Requisição mal formada.
     * @throws UnauthorizedHttpException  Requisição requer autenticação.
     * @throws AccessDeniedHttpException  O acesso ao recurso foi negado.
     * @throws NotFoundHttpException  Recurso não encontrado.
     * @throws UnprocessableEntityHttpException  Requisição não processável.
     * @return void  Erro Interno.
     *
     */
    public function purchasesMeGet();

    /**
     * Operation purchasesPost
     *
     * Cria uma compra
     *
     * @param  PurchasePost $purchase   (required)
     *
     * @return PurchaseAdd  Operação realizada com sucesso.
     *
     * @throws BadRequestHttpException  Requisição mal formada.
     * @throws UnauthorizedHttpException  Requisição requer autenticação.
     * @throws AccessDeniedHttpException  O acesso ao recurso foi negado.
     * @throws NotFoundHttpException  Recurso não encontrado.
     * @throws UnprocessableEntityHttpException  Requisição não processável.
     * @return void  Erro Interno.
     *
     */
    public function purchasesPost(PurchasePost $purchase);
}
