<?php
/**
 * LojasApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketplace
 *
 * API Cloud Loyalty LTM - Webpremios
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Api;

use Swagger\Server\Model\Stores;
use Swagger\Server\Model\BusinessErrorMessage;
use Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\HttpKernel\Exception\UnprocessableEntityHttpException;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;

/**
 * LojasApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  Swagger\Server\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
interface LojasApiInterface
{

    /**
     * Sets authentication method access_token
     *
     * @param string $value Value of the access_token authentication method.
     *
     * @return void
     */
    public function setaccess_token($value);

    /**
     * Sets authentication method client_id
     *
     * @param string $value Value of the client_id authentication method.
     *
     * @return void
     */
    public function setclient_id($value);

    /**
     * Operation storesGet
     *
     * Recurso utilizado para retornar as lojas do catálogo
     *
     *
     * @return Stores  Operação realizada com sucesso.
     *
     * @throws BadRequestHttpException  Requisição mal formada.
     * @throws UnauthorizedHttpException  Requisição requer autenticação.
     * @throws AccessDeniedHttpException  O acesso ao recurso foi negado.
     * @throws NotFoundHttpException  Recurso não encontrado.
     * @throws UnprocessableEntityHttpException  Requisição não processável.
     * @return void  Erro Interno.
     *
     */
    public function storesGet();
}
